/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zhjn' at '7/17/16 4:51 PM' with Gradle 2.14
 *
 * @author zhjn, @date 7/17/16 4:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
